version: '3.5'

services:
  db:
    image: mysql:5.7
    container_name: wordpress_db
    volumes:
      - db_data:/var/lib/mysql
      - ./db/backup.sql:/docker-entrypoint-initdb.d/backup.sql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    networks:
      - wpsite

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress
    ports:
      - 8000:80
    restart: always
    volumes:
      - ./:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
    networks:
      - wpsite

  phpmyadmin:
    container_name: wordpress_phpmyadmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 5555:80
    restart: always
    networks:
      - wpsite

networks:
  wpsite:
volumes:
  db_data: